//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DRrect
{
    [Serializable]
    public class EventMsg : Message
    {
        public const string k_RosMessageName = "d_rrect/Event";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public string data;

        public EventMsg()
        {
            this.header = new Std.HeaderMsg();
            this.data = "";
        }

        public EventMsg(Std.HeaderMsg header, string data)
        {
            this.header = header;
            this.data = data;
        }

        public static EventMsg Deserialize(MessageDeserializer deserializer) => new EventMsg(deserializer);

        private EventMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "EventMsg: " +
            "\nheader: " + header.ToString() +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
